#!/usr/bin/env sh
#
#
# launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
sudo yabai --load-sa

# $HOME/.config/yabai/create_spaces.sh

# default layout (can be bsp, stack or float)
yabai -m config layout bsp
yabai -m config window_placement second_child

#general
# yabai -m rule --add app="^${applications}$"    manage=on layer=below
yabai -m config window_topmost off
yabai -m config window_shadow float

yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9
yabai -m config split_ratio 0.50
yabai -m config auto_balance off

# padding set to 12px
yabai -m config top_padding 4
yabai -m config bottom_padding 4
yabai -m config left_padding 4
yabai -m config right_padding 4
yabai -m config window_gap 4

yabai -m config external_bar all:26:0

# center mouse on window with focus
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize
# yabai -m config mouse_drop_action swap


# when window is dropped in center of another window, swap them (on edges it will split it)

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
